### ISSUE TITLE
please check i cont bulid application.

### ISSUE THREAD

**Issue by himanshujjp** [pnkr01/EV-Sathi.#1]
![Screenshot_20221229_121924](https://user-images.githubusercontent.com/62508138/209914649-bf416058-ab12-43eb-a10e-422e37bdf717.png)

**Comment by pnkr01** [comment]
Hi, @himanshujjp  thank you for showing interest in the EV Sathi App. For the introduction, I used a curved splash screen that wasn't null-safe. will change that and fix it. If you want to learn, you can try contributing.

**Comment by himanshujjp** [comment]
thx u brother
